baseurl = ""
title = "James King | Projects and Thoughts"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
    
#sdisqusShortname = "yourdiscussshortname"

[params]
    author = "James King"
    info = 'I do "Smart Computer Things" according to my wife'
    description = "James King's Personal Website"
    keywords = "blog,developer,personal,it,infrastructure"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    #custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/king-jam/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/james-king-a6ba6b1a/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/JamesRKing4/"
[[params.social]]
    name = "E-Mail"
    icon = "fas fa-envelope fa-2x"
    weight = 4
    url = "mailto:james.r.king4@gmail.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"